default:
  image: docker:latest
  services:
    - name: docker:dind
  before_script:
    - docker login -u "snadn" -p "$HUB_REGISTRY_PASSWORD"

variables:
  # DOCKER_HOST: tcp://docker:2375/
  DOCKER_CLI_EXPERIMENTAL: enabled
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_DRIVER: overlay2

docker-build-master:
  stage: build
  script:
    - docker info
    - docker build --network host --pull -t "snadn/buildx" .
    - docker push "snadn/buildx"
  only:
    - master
