default:
  image: docker:latest
  services:
    - name: docker:dind
  before_script:
    - docker login -u "snadn" -p "$HUB_REGISTRY_PASSWORD"

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

docker-build-master:
  stage: build
  script:
    - docker build --add-host docker:`grep docker /etc/hosts | awk 'NR==1{print $1}'` --network host --pull -t "snadn/buildx" .
    - docker push "snadn/buildx"
  only:
    - master
